---
# tasks file for os_neutron
- name: Install the packages
  apt:
    pkg: "{{ item }}"
    state: latest
    #update_cache: yes
    cache_valid_time: 600
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: neutron_compute_apt_packages
  tags:
     - neutron-compute-apt-packages


